### ISSUE TITLE
Add ggplot2-like Features for geom_raster and geom_sf in GMT.jl

### ISSUE THREAD

**Issue by Jigyasu4indp** [GenericMappingTools/GMTjl_doc#2] opened 2024-11-10 09:13 UTC

**Comment by Jigyasu4indp** [comment] 2024-11-10 09:18
First of all, thank you very much for developing the GMT package. Could you consider expanding the documentation to comprehensively cover all features, including base maps, raster data visualization over base maps, global overlays, and enhanced data visualization? It would be particularly helpful to include examples of features like color bars, scale bars, facet wrapping, and facet grids.

Additionally, could you please add functionality similar to geom_raster and geom_sf from ggplot2 in R? This would be a tremendous aid in producing high-quality plots for publication and promoting Julia as a tool for geospatial visualization.

**Comment by joa-quim** [comment] 2024-11-10 19:43
Closing as this is a duplicate of
https://github.com/GenericMappingTools/GMT.jl/issues/1585

**Closed as completed by joa-quim** 2024-11-10 19:43 UTC
